### ISSUE TITLE
Feedback!

### ISSUE THREAD

**Issue by nightfury1103** [nightfury1103/P4DS-CQ19-FinalProject#21]

**Comment by nightfury1103** [comment]
Đồ án đã hoàn thành. Đây là nơi các bạn nhận xét bài làm của nhóm mình. Chúng mình chân thành cảm ơn bạn đã ghé thăm <3

**Comment by Taka304** [comment]
MSSV: 19120267 - Tên: Hoàng Dược Lam 
Mình đã đọc và cũng đã thử clone bài làm của nhóm để chạy thử và thấy nhóm có những câu hỏi rất hay, cũng như đa dạng trong các câu hỏi phân tích, các phần markdown viết rất kĩ.
Tuy nhiên, mình có một số nhận xét như sau, nhóm có thể đọc và cân nhắc chỉnh sửa nhé:
 - Ở phần code phân bố các cột dạng số, mình nghĩ các bạn có thể sử dụng phương thức .describe() để lấy ra các giá trị về tính phân bố rồi nhận xét về nó, sau đó mới sử dụng 1 phần code ở hàm calculate_quartile() lấy ra giá trị thiếu rồi nhận xét tiếp sẽ giúp code ngắn gọn và clean hơn
 - Ở câu hỏi 'Khoảng thời gian xe đạp thường được dùng nhiều nhất và ít nhất?', mình thấy nhóm có làm nhiều hướng phân tích, nên bạn có thể ghi các hướng sẽ phân tích ở ngay dưới câu hỏi (trên các bước làm) sẽ giúp dễ đọc hơn
- Phần biểu đồ có snow_fall và rain_fall, thì mình nhận thấy những tháng có tuyết vẫn có thông tin về mưa (mình đã thử clone bài của bạn và chạy thử một số cell), nhưng thông tin trên plot thì lại chỉ hiện hoặc 1 trong 2. Có vẻ là bạn đã plot giá trị nào lớn hơn trong mỗi tháng, nhưng mình thấy đây là 2 cột có ý nghĩa khác nhau, không thể so sánh gộp lại như vậy nên điều đó không hợp lý. Bạn nên thử làm cột đôi về phần này sẽ chính xác hơn
- Phần biểu đồ season nên set lại đúng tên thay vì 0,1,2,3; hoặc ghi chú quy định đặt tên trước khi vẽ biểu đồ để dễ hiểu hơn (ghi chú ở tiền xử lý hơi xa quá)
- Các biểu đồ trong bài rất đa dạng. Phần ‘Lượng xe đạp theo từng mùa/ từng tháng có sự thay đổi như thế nào?’ có câu hỏi, biểu đồ và khám phá hay
- Câu bức xạ, sau khi đọc code, mình nghĩ nó nói về trung bình các giờ (theo tháng) có bức xạ cao thì sẽ chính xác hơn, do nó lấy ra những dòng dữ liệu có bức xạ cao/không cao – tức là lấy ra các giờ trong ngày, nên khi trong nhóm nó không còn theo ngày nữa. Câu này cũng nên làm biểu đồ cột đôi
- Câu tầm nhìn, vì dữ liệu thống kê theo từng giờ của ngày, nên khi lấy ra các dòng, dữ liệu đang bị ràng buộc theo giờ, vì vậy nên phần trung bình cũng đang tính theo giờ, không hẳn là theo ngày cho lắm. các bạn nên chỉnh sửa phù hợp lại nhé

Mình có nhận xét hơi nhiều và dài dòng, mong các bạn đọc và thấy ý nào hợp lý thì sửa vô bài làm của mình nhé!

**Comment by Tranmyhan** [comment]
- Lỗi chính tả, phần mục đích lựa chọn dữ liệu này, ý 2, từ "đầy dẫy"; phần ý nghĩa các cột, cột "Rainfall" và "Snowfall", từ "thời điêm".
- Lỗi type, phần người ta thu thập dữ liệu như thế nào, ý 1.
- Phần dữ liệu các dòng có bị lặp hay không, mình thấy bạn viết giải thích dự đoán không đúng vì cột "Date" vẫn có giá trị giống nhau, kết hợp thêm cột "Hour" thì mới khác (1 ngày 24 giờ, 1 giá trị của "Date" có thể xuất hiện 24 lần).
- Nếu không dùng học máy, thì các cột "Seasons", "Holiday", "Functioning Day" mình nghĩ không cần chuyển về dạng số, vì chuyển về dạng số thì khi vẽ biểu đồ phải chú thích thêm các số đó đại diện cho giá trị nào, không có chú thích rất khó hiểu vì toàn 0,1....
- Phần Với mỗi cột có kiểu dữ liệu dạng số (numerical), các giá trị được phân bố như thế nào, có thể sử dụng .describe() có sẵn trong thư viện pandas để tính các giá trị min, max, phân vị 25, 50, 75, không cần code hàm tính.
- Các cột "Hour", "Seasons", "Holiday", "Functioning Day" mình thấy các bạn phân vào cả 2 cột có dữ liệu dạng numerical và categorical, 1 trong 2 thôi chứ nhỉ.
- Câu 1: 
Xem lại phần nhận xét biểu đồ tương quan xe đạp giữa ngày nghỉ và ngày đi làm, hình như các bạn nhầm màu rồi.
Phần chia 1 ngày thành 5 giai đoạn, mình nghĩ biểu đồ đường sẽ dễ nhìn hơn, mỗi đường là 1 giai đoạn.
- Biểu đồ nên có đủ tên của cả 2 trục.
- Mấy bạn xem lại trình bày nha, tiêu đề phần câu hỏi, có câu không in đậm, có câu in đậm.
- Nên xóa các cell trống trong bài.

Mong góp ý của mình có thể giúp các bạn phần nào.

**Comment by duylocky2k1** [comment]
@Taka304 @Tranmyhan  Cảm ơn các đóng góp của các bạn nha 💯 . Nhóm mình chỉ mong được góp ý thật nhiều để có thể chỉnh sửa hoàn thiện bài tốt hơn thôi hehe ^^
